---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(clusterProfiler)
library(DOSE)
library(ReactomePA)
library(readr)

path = "~/AA_PostDoc/human-metnet/"


rxns  <- read_csv(paste0(path,"data/recon2_rxn_info.csv")) %>% column_to_rownames("X1")
genes <- read_csv(paste0(path,"data/recon2_genes_to_rxns.csv")) %>% column_to_rownames("X1")
negative_fold_change  <- read_csv(paste0(path,"results/PKU_recon2rxn_top_negative_fold_change.csv")) %>% column_to_rownames("X1")
positive_fold_change  <- read_csv(paste0(path,"results/PKU_recon2rxn_top_positive_fold_change.csv")) %>% column_to_rownames("X1")

get_genes <- function(a_rxn){return(genes %>% filter(str_detect(Reactions, regex(a_rxn, ignore_case = T))) %>%
                            .[["Gene_ID"]] %>% str_trim %>% str_extract_all("^\\d+") %>% unlist())}
get_genes_by_centrality <- function(FC){
                                      centrality_to_genes <- function(centrality_names){FC[[centrality_names]]  %>% map(get_genes) %>% unlist %>% unique %>% return}
                                      FC %>% colnames() -> centrality_names
                                     centrality_names %>%  map(centrality_to_genes) %>% purrr::set_names(centrality_names) -> genes_by_centrality
                                     return(genes_by_centrality)}

```

log2(ce_ko/ce_wt)


```{r fig.height=4, fig.width=20, message=FALSE, warning=FALSE}
read_csv(paste0(path,"results/PKU_recon2rxn_top_positive_fold_change.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality  %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/LOG_top_PHETHPTOX2.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality  %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
```
```{r}
read_csv(paste0(path, "results/tmp.reacciones_pku_controles.csv"))
```


```{r fig.height=4, fig.width=20, message=FALSE, warning=FALSE}

read_csv(paste0(path,"results/FC_top_ASCBOX.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality  %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PEAMNO.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality  %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_D3AIBTm.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality  %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_DPMVDc.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_ENGASEly.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PACCOAL.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PPOR.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_r0545.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_r0547.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_RN0027C.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PHACCOAGLNAC.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PHETA1m.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PHETA1.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot
read_csv(paste0(path,"results/FC_top_PHYCBOXL.csv")) %>% column_to_rownames("X1") %>% get_genes_by_centrality %>% compareCluster(fun='enrichDGN', pvalueCutoff=0.01)  %>% dotplot

 


```
###########################################################






