---
title: "R Notebook"
output: html_notebook
---

Automatic annotations
```{r message=FALSE, warning=FALSE}
library(tidyverse)
path = "~/AA_PostDoc/human-metnet/"
importing <- function(a_path){read_csv(paste0(path,a_path)) %>% dplyr::select(-"X1")  %>% remove_rownames %>% return()}

genes.recon3 <- importing("data/recon3_genes_to_reactionIDs.csv")
rxns.recon3 <- importing("data/recon3_reactions_metadata.csv")
genes.NAMU <- importing("data/NAMU_genes_to_reactionIDs.csv")
rxns.NAMU <- importing("data/NAMU_reactions_metadata.csv")

get_long_table_rxn_genes <- function(my_rxns, genes){
                                 get_genes <- function(a_rxn){return(genes %>% filter(str_detect(Reactions, regex(a_rxn, ignore_case = T))) %>%
                                                    .[["Gene_ID"]] %>% str_trim %>% str_extract_all("^\\d+") %>% unlist())}
                                 my_collapse <- function(a_string){paste0(a_string, collapse = ", ")}
                                      my_rxns  %>% map(get_genes )%>% purrr::set_names(my_rxns) %>%
                                       lapply( my_collapse) %>%  as_tibble() %>% tidyr::gather(key="ID", value="auto_anno_genes") -> long_table
                                      long_table %>% return()}

get_long_table_rxn_genes(rxns.recon3$rxn_ids, genes.recon3) -> recon3_IDs_genes
get_long_table_rxn_genes(rxns.NAMU$rxn_ids, genes.NAMU)     -> NAMU_IDs_genes
```


```{r message=FALSE, warning=FALSE}
library(magrittr)
NAMU_IDs_genes$ID         %<>% str_replace_all(',|_','') 
recon3_IDs_genes$ID  %<>%str_replace_all(',|_','') 
#find_recon3_annot <- function(a_rxn_pattern, ){str_detect(genes$ID, regex(a_rxn_pattern, ignore_case = T)) %>% which}
auto_anno_recon3 <- data.frame()
for(i in 1:nrow(recon3_IDs_genes)){
 str_detect(NAMU_IDs_genes$ID, regex(paste0('^',recon3_IDs_genes[[i,'ID']], collapse = ''), ignore_case = T)) %>% which -> idxs
data.frame(row.names =  NAMU_IDs_genes$ID[idxs]) %>% mutate(auto_anno_recon3 = recon3_IDs_genes[[i,'auto_anno_genes']]) %>%
  rownames_to_column('ID')-> hola
rbind(auto_anno_recon3, hola) -> auto_anno_recon3
}

full_join(auto_anno_recon3, NAMU_IDs_genes) -> NAMU_genes


NAMU_genes  %<>% set_names(c("ID", "recon3_genes", "Lewis2010_genes"))
```

```{r message=FALSE, warning=FALSE}
setwd("~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/functional_analysis_of_hubs")
library(tidyverse)

extra_genes = data.frame(ID = c("3DPHBH2_Neuron", "NH3tm_Neuron", 'AASAD3m', "SPODMm", "COQ3m_Neuron", "H2Otm_Neuron", "Htm_Neuron") ,
                         KEGG_genes   =	c(NA, NA,501, 6648, 51805, 343, paste(9481, 7352, 7351, 7350, sep = ", ")),
                         VMH_gene_IDs = NA)
mas_genes <- read_csv("genes_q_faltan.csv")  %>%  dplyr::select(c("ID","VMH_gene_IDs","KEGG_genes"))
genes <- read_csv('table_of_genes_from_VMH_KEGG.csv') %>%  dplyr::select(c("ID","VMH_gene_IDs","KEGG_genes")) %>% rbind(extra_genes) %>% rbind(mas_genes) 

full_join(NAMU_genes, genes) ->NAMU_all_genes
```

```{r}
path_figure_1 = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_1/"

path_figure_2 = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_2/"
path_figure_3 = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_3/"
id_name <- read_rds(paste0(path_figure_1, "all_data.rds")) %>% .[[1]] %>%  dplyr::select(c("ID", "Name" ))
Centrality0      <- read_csv(paste0(path_figure_2, "total_centrality_by_node.csv"))  %>% filter(total.abs.centrality > 0) 
Optimality0      <- read_csv(paste0(path_figure_3, "optimality_values.csv"))

c('PGM', 'ACYP', 'PGI', 'PGK','PYK', 'HEX1', 'DPGase', 'TPI', 'PFK', 'ENO', 'GAPD', 'DPGM', 'FBA', 'G3PD2m' ,
'ACYP_Neuron', 'DPGM_Neuron', 'DPGase_Neuron', 'ENO_Neuron', 'FBA_Neuron', 'G3PD2m_Neuron', 'GAPD_Neuron', 'HEX1_Neuron', 'PFK_Neuron', 'PGI_Neuron', 'PGK_Neuron', 'PGM_Neuron', 'PYK_Neuron', 'TPI_Neuron' ,
'ATPS4m_Neuron', 'CYOOm2_Neuron', 'CYOR-u10m_Neuron', 'NADH2-u10m_Neuron', 'PPA_Neuron', 'PPAm_Neuron' ,
'PPAm', 'ATPS4m', 'CYOOm2', 'CYOR-u10m', 'NADH2-u10m', 'PPA') -> subsystems

Optimality0[!(Optimality0$ID %in% subsystems),] -> Optimality
Centrality0[!(Centrality0$ID %in% subsystems),] -> Centrality
library(magrittr)




Optimality %<>% dplyr::rename( Optimality = total) %>% dplyr::select(c("ID", 'Optimality'))
Centrality %<>% dplyr::rename( Centrality = total.abs.centrality)
```

```{r}
library(scales)
library(magrittr)
full_join(Centrality,Optimality) -> all


all$Centrality %<>% rescale(to = c(0,1))
all$Optimality %<>% rescale(to = c(0,1))


inner_join(all, NAMU_all_genes)-> IDs_centrality_optimality # %>% writexl::write_xlsx('IDs_centrality_optimality.xlsx')
```

```{r}
setwd("~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/functional_analysis_of_hubs")

path_figure_2 = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_2/"
readRDS(paste0(path_figure_2, "all_data.rds")) %>% .[["delta_geometric"]] %>% dplyr::select(c(ID,Name, Reaction,`Node type`)) -> all_data


inner_join(IDs_centrality_optimality, all_data) %>% filter(`Node type` == "Astrocyte") -> Astrocyte_IDs_centrality_optimality
inner_join(IDs_centrality_optimality, all_data) %>% filter(`Node type` == "Neuron")  -> Neuron_IDs_centrality_optimality

Astrocyte_IDs_centrality_optimality%>% writexl::write_xlsx('Astrocyte_IDs_centrality_optimality.xlsx')
Neuron_IDs_centrality_optimality%>% writexl::write_xlsx('Neuron_IDs_centrality_optimality.xlsx')

```

```{r message=FALSE, warning=FALSE}
path_Hyperhubs.csv = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_4/Hyperhubs.csv"
path_Optimalhubs.csv = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_4/Optimalhubs.csv"
path_Centralhubs.csv = "~/AA_PostDoc/human-metnet/results/stimulated_NAMU_results_analysis/Figure_4/Centralhubs.csv"
optimalhubs <- read_csv(path_Optimalhubs.csv)
centralhubs <- read_csv(path_Centralhubs.csv)
hyperhubs <- read_csv(path_Hyperhubs.csv)

inner_join(optimalhubs, NAMU_all_genes) %>% writexl::write_xlsx('optimalhubs.xlsx')
inner_join(centralhubs, NAMU_all_genes)%>%writexl::write_xlsx('centralhubs.xlsx')
inner_join(hyperhubs, NAMU_all_genes)%>%writexl::write_xlsx('hyperhubs.xlsx')
```










